using System;
using System.Collections.Generic;

namespace Utils.Tools
{
    public class RandomTextGenerator
    {
        private readonly List<string> m_Texts = new()
        {
            "Mission complete! You've saved the village from danger.",
            "Toast: Your bravery is legendary!",
            "Find the lost sword in the ancient ruins!",
            "Notification: New mission available at the board.",
            "Congratulations! You've unlocked a new level.",
            "Mission: Escort the merchant to the safe city.",
            "Toast: Your archery skills are impressive!",
            "Defeat the dragon terrorizing the mountains!",
            "Warning! An ambush awaits in the forest.",
            "Notification: You've received 100 gold coins.",
            "Explore the dark cave and find the hidden treasure!",
            "Toast: Nobody brews potions like you!",
            "Mission: Rescue the villagers trapped in the mine.",
            "You've won an epic duel in the arena!",
            "Notification: Your armor has been repaired.",
            "Find the cursed pirate's lost map!",
            "Toast: Your magic has lit up the darkness!",
            "Mission: Defend the castle from the enemy invasion.",
            "You've discovered an ancient artifact!",
            "Notification: New skill unlocked: Critical Strike.",
            "Travel to the neighboring kingdom and negotiate peace!",
            "Toast: Your swordsmanship is unmatched!",
            "Mission: Steal the dark wizard's scepter.",
            "You've evaded a deadly trap!",
            "Notification: Your inventory is almost full.",
            "Explore the desert in search of the secret oasis!",
            "Toast: Your courage inspires all!",
            "Mission: Find the wise hermit in the mountains.",
            "You've defeated a powerful boss!",
            "Notification: You've risen to the rank of hero.",
            "Collect 10 mystic herbs for the potion!",
            "Toast: Your strategy was flawless!",
            "Mission: Free the spirit trapped in the temple.",
            "You've found a secret shortcut!",
            "Notification: New mount available at the stable.",
            "Investigate the strange events in the village!",
            "Toast: Your cunning fooled the enemy!",
            "Mission: Recover the stolen grimoire.",
            "You've survived a magical storm!",
            "Notification: Your weapon has been upgraded.",
            "Search for the golden key in the labyrinth!",
            "Toast: Your endurance is astonishing!",
            "Mission: Protect the caravan from bandits.",
            "You've disarmed a clever trap!",
            "Notification: You've earned an honorary title.",
            "Find the traitor in the royal council!",
            "Toast: Your leadership unites the troops!",
            "Mission: Destroy the demonic portal.",
            "You've avoided a surprise attack!",
            "Notification: New side quest unlocked.",
            "Explore the catacombs for ancient relics!",
            "Toast: Your speed is unstoppable!",
            "Mission: Train with the sword master.",
            "You've found a hidden chest!",
            "Notification: Your magical energy is at its peak.",
            "Investigate the alchemist's disappearance!",
            "Toast: Your wit solved the riddle!",
            "Mission: Cross the poisonous swamp.",
            "You've won a glorious tournament!",
            "Notification: New armor available at the forge.",
            "Search for the power crystal in the tower!",
            "Toast: Your kindness has saved lives!",
            "Mission: Defeat the wolves attacking the livestock.",
            "You've escaped an enemy prison!",
            "Notification: You've received a message from the king.",
            "Find the antidote for the plague!",
            "Toast: Your precision is deadly!",
            "Mission: Spy on the enemy army.",
            "You've discovered a lost city!",
            "Notification: Your experience level has increased.",
            "Gather materials to build a bridge!",
            "Toast: Your charisma convinced everyone!",
            "Mission: Free the chained dragon.",
            "You've overcome an impossible challenge!",
            "Notification: New trade route unlocked.",
            "Explore the active volcano for clues!",
            "Toast: Your patience was key!",
            "Mission: Find the lost child in the forest.",
            "You've dispelled an evil curse!",
            "Notification: Your stamina has improved.",
            "Search for the ancient scroll in the library!",
            "Toast: Your sacrifice won't be forgotten!",
            "Mission: Stop the undead invasion.",
            "You've earned the loyalty of an ally!",
            "Notification: New reward available.",
            "Investigate the secret cult in the city!",
            "Toast: Your magical power is overwhelming!",
            "Mission: Recover the fallen banner.",
            "You've solved an ancient mystery!",
            "Notification: Your team is ready for battle.",
            "Find the entrance to the underground kingdom!",
            "Toast: Your honor shines like the sun!",
            "Mission: Protect the oracle from assassins.",
            "You've conquered an enemy fortress!",
            "Notification: New passive skill unlocked.",
            "Search for the source of the magical fog!",
            "Toast: Your determination is unbreakable!",
            "Mission: Find the guardian of the forest.",
            "You've completed an epic quest!"
        };

        private readonly Random m_Random = new();

        public string GetRandomText()
        {
            return m_Texts[m_Random.Next(m_Texts.Count)];
        }
    }
}